### PR TITLE
Fix transaction rollback discarding exec error messages

### PR DESCRIPTION
**Pull request by Zacho2**
Thanks for this great Go package.

Currently, when an error occurs during `err = tx.Exec(...`, the original error message is discarded when err is assigned to `err = tx.Rollback()`, and nil is shown for the error if the rollback succeeds. The changes in this pull request keeps the Exec and Rollback error message.

Experienced this with postgres when trying to run migrations with invalid SQL syntax. Output:

`Migration failed: Error while running migration 2_init (up): Error executing statement: %!s(<nil>)
CREATE TABLE IF NOT ETS sometable (
    confirmation_token character varying(50),
    confirmed boolean DEFAULT false,
);
`

Note that the error from `tx.Exec` shows as nil.

### CODE REVIEW

**Comment by F21** [comment]
Great idea! Do you mind applying the same changes to the other drivers and then squash the commits?

**Comment by Zacho2** [comment]
Which other drivers? I modified Postgres and SQLite. MySQL and Phoenix don't appear to have a rollback feature with the driver.

**Comment by F21** [comment]
Oops, sorry! I just looked at the code for Phoenix and MySQL and they don't use transactions (because they don't support running DDL statements in a transaction).

Thanks for your PR! 😄

**Comment by Zacho2** [comment]
No problem 👍

**Pull request merged**
